apiVersion: v1
kind: Secret
metadata:
  name: notification
  namespace: site-monitor
  labels:
    app.kubernetes.io/name: notification
    app.kubernetes.io/part-of: site-monitor
type: Opaque
stringData:
  NOTIFICATION_TG_BOT_TOKEN: "example-telegram-bot-token"
  NOTIFICATION_TG_CHAT_ID: "000000000"
