apiVersion: v1
kind: Service
metadata:
  name: notification
  namespace: site-monitor
  labels:
    app.kubernetes.io/name: notification
    app.kubernetes.io/part-of: site-monitor
spec:
  selector:
    app.kubernetes.io/name: notification
  ports:
    - name: http
      port: 8081
      targetPort: http
