apiVersion: v1
kind: Secret
metadata:
  name: monitor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "monitor-service.labels" (dict "component" "monitor" "root" .) | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.monitor.databaseUrl | quote }}
