apiVersion: v1
kind: Service
metadata:
  name: monitor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "monitor-service.labels" (dict "component" "monitor" "root" .) | nindent 4 }}
spec:
  selector:
    {{- include "monitor-service.selectorLabels" (dict "component" "monitor") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.monitor.ports.http }}
      targetPort: http
    - name: grpc
      port: {{ .Values.monitor.ports.grpc }}
      targetPort: grpc
