apiVersion: v1
kind: ConfigMap
metadata:
  name: notification
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "monitor-service.labels" (dict "component" "notification" "root" .) | nindent 4 }}
data:
  KAFKA_BROKER: {{ .Values.notification.config.kafkaBroker | quote }}
  KAFKA_TOPIC: {{ .Values.notification.config.kafkaTopic | quote }}
  KAFKA_GROUP_ID: {{ .Values.notification.config.kafkaGroupId | quote }}
  KAFKA_DLQ_TOPIC: {{ .Values.notification.config.kafkaDlqTopic | quote }}
  NOTIFICATION_HTTP_ADDR: {{ .Values.notification.config.httpAddr | quote }}
  NOTIFICATION_LOG_LEVEL: {{ .Values.notification.config.logLevel | quote }}
  NOTIFICATION_RETRY_ENABLED: {{ .Values.notification.config.retryEnabled | quote }}
  NOTIFICATION_RETRY_MAX_ATTEMPTS: {{ .Values.notification.config.retryMaxAttempts | quote }}
  NOTIFICATION_RETRY_INTERVAL: {{ .Values.notification.config.retryInterval | quote }}
  NOTIFICATION_RETRY_MULTIPLIER: {{ .Values.notification.config.retryMultiplier | quote }}
