apiVersion: v1
kind: Secret
metadata:
  name: notification
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "monitor-service.labels" (dict "component" "notification" "root" .) | nindent 4 }}
type: Opaque
stringData:
  NOTIFICATION_TG_BOT_TOKEN: {{ .Values.notification.telegram.botToken | quote }}
  NOTIFICATION_TG_CHAT_ID: {{ .Values.notification.telegram.chatId | quote }}
