apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: site-monitor
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/part-of: site-monitor
spec:
  selector:
    app.kubernetes.io/name: gateway
  ports:
    - name: http
      port: 8082
      targetPort: http
