apiVersion: v1
kind: Secret
metadata:
  name: postgres
  namespace: site-monitor
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: site-monitor
type: Opaque
stringData:
  POSTGRES_USER: "example-user"
  POSTGRES_PASSWORD: "example-password"
  POSTGRES_DB: "site_monitor_db"
