apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "monitor-service.labels" (dict "component" "postgres" "root" .) | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "monitor-service.selectorLabels" (dict "component" "postgres") | nindent 4 }}
  ports:
    - name: postgres
      port: {{ .Values.postgres.port }}
      targetPort: postgres
