apiVersion: v1
kind: Secret
metadata:
  name: monitor
  namespace: site-monitor
  labels:
    app.kubernetes.io/name: monitor
    app.kubernetes.io/part-of: site-monitor
type: Opaque
stringData:
  DATABASE_URL: "postgres://example-user:example-password@postgres:5432/site_monitor_db?sslmode=disable"
