apiVersion: v1
kind: Service
metadata:
  name: monitor
  namespace: site-monitor
  labels:
    app.kubernetes.io/name: monitor
    app.kubernetes.io/part-of: site-monitor
spec:
  selector:
    app.kubernetes.io/name: monitor
  ports:
    - name: http
      port: 8080
      targetPort: http
    - name: grpc
      port: 9090
      targetPort: grpc
