monitor:
  databaseUrl: "postgres://example-user:example-password@postgres:5432/site_monitor_db?sslmode=disable"
notification:
  telegram:
    botToken: example-telegram-bot-token
    chatId: "000000000"
postgres:
  auth:
    user: example-user
    password: example-password
    database: site_monitor_db
